### ISSUE TITLE
Add Unit Tests

### ISSUE THREAD

**Issue by NeonDaniel** [NeonGeckoCom/neon-lang-plugin-google_translate#1]
Add unit testing of Detector/Translator Modules.

tests directory and github automation should be added

Example:
https://github.com/NeonGeckoCom/neon-lang-plugin-libretranslate

**Comment by NeonMariia** [comment]
contributing to https://github.com/NeonGeckoCom/neon-lang-plugin-google_translate/issues/1

**Comment by NeonDaniel** [comment]
#6 added tests, automation still needed
